# file: maxscale-rhel.yml 

- include: selinux.yml

- name: install maxscale repo
  yum: name=http://downloads.mariadb.com/enterprise/{{ enterprise_token }}/generate/10.0/mariadb-enterprise-repository.rpm state=present

- name: install maxscale
  yum: name=maxscale state=present    
