- include: selinux.yml
  when: ansible_os_family == 'RedHat'

- include: galera-rhel.yml
  when: ansible_os_family == 'RedHat'

- include: galera-deb.yml
  when: ansible_os_family == 'Debian'

- name: Install MariaDB configuration template
  template: src=galera.cnf dest=/etc/my.cnf.d/

- include: bootstrap.yml
  when: is_primary
